# Generated by Django 3.1.4 on 2020-12-26 11:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('homepage', '0002_coffee_desc'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='coffee',
            name='desc',
        ),
    ]
