# Generated by Django 3.1.4 on 2020-12-24 12:58

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Bakery',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='', max_length=40)),
                ('price', models.IntegerField(default=0)),
                ('count', models.IntegerField(default=1)),
                ('is_takeout', models.BooleanField(default=False)),
            ],
        ),
    ]
