# Generated by Django 3.1.4 on 2020-12-24 14:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('homepage', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='bakery',
            name='count',
        ),
        migrations.RemoveField(
            model_name='bakery',
            name='is_takeout',
        ),
        migrations.AddField(
            model_name='bakery',
            name='stock',
            field=models.IntegerField(default=0),
        ),
    ]
