# Generated by Django 3.1.4 on 2020-12-24 15:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('homepage', '0002_auto_20201224_2302'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='bakery',
            name='id',
        ),
        migrations.AddField(
            model_name='bakery',
            name='key',
            field=models.BigAutoField(default=1, primary_key=True, serialize=False),
            preserve_default=False,
        ),
    ]
