# Generated by Django 3.2.3 on 2021-05-16 10:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('homepage', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='CoffeeBeen',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='', max_length=30)),
                ('stock', models.IntegerField(default=0)),
                ('last_purchased', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
