# Generated by Django 3.2.3 on 2021-05-16 10:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('homepage', '0002_coffeebeen'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='coffeebeen',
            name='last_purchased',
        ),
    ]
