# Generated by Django 3.2.3 on 2021-05-18 09:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('homepage', '0003_alter_bugger_id'),
    ]

    operations = [
        migrations.CreateModel(
            name='Id_s',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('id_s', models.IntegerField(default=0)),
            ],
        ),
    ]
