# Generated by Django 3.2.3 on 2021-05-18 10:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('homepage', '0004_id_s'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Bugger',
            new_name='Burger',
        ),
    ]
