# Generated by Django 3.2.3 on 2021-05-18 15:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('asgmts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='sneaker',
            name='price',
            field=models.IntegerField(default=0),
        ),
    ]
