# Generated by Django 3.1.4 on 2020-12-25 10:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('homepage', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Coffee',
            new_name='Lol',
        ),
    ]
