# Generated by Django 3.2.3 on 2021-05-19 15:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mission_1', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='buger',
            name='set_menu',
        ),
    ]
