# Generated by Django 3.2.3 on 2021-05-19 15:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mission_1', '0002_remove_buger_set_menu'),
    ]

    operations = [
        migrations.AddField(
            model_name='buger',
            name='set_menu',
            field=models.BooleanField(default=False),
        ),
    ]
