# Generated by Django 3.2.3 on 2021-05-18 06:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('intro', '0002_rename_coffe_coffee'),
    ]

    operations = [
        migrations.CreateModel(
            name='Fruit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='', max_length=50)),
                ('stock', models.IntegerField(default=0)),
            ],
        ),
    ]
