# Generated by Django 3.2.3 on 2021-05-18 04:50

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Coffee',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='Unknow', max_length=30)),
                ('price', models.IntegerField(default=0)),
                ('is_caffein', models.BooleanField(default=True)),
                ('is_ice', models.BooleanField(default=False)),
                ('img_url', models.CharField(default='', max_length=100)),
            ],
        ),
    ]
