# Generated by Django 3.2.3 on 2021-05-18 04:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('homepage', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='coffee',
            name='img_url',
            field=models.CharField(default='', max_length=100, null=True),
        ),
    ]
