# Generated by Django 3.2.3 on 2021-05-18 04:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('homepage', '0003_alter_coffee_img_url'),
    ]

    operations = [
        migrations.AlterField(
            model_name='coffee',
            name='img_url',
            field=models.CharField(blank=True, default='', max_length=100, null=True),
        ),
    ]
