# Generated by Django 3.2.3 on 2021-05-18 13:15

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('homepage', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Fruit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='', max_length=50)),
                ('price', models.IntegerField(default=0)),
                ('origin', models.CharField(default='KR', max_length=3)),
                ('packing_date', models.DateField(default=datetime.date.today)),
            ],
        ),
    ]
