# Generated by Django 3.2.3 on 2021-05-18 13:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('homepage', '0002_fruit'),
    ]

    operations = [
        migrations.CreateModel(
            name='BaskinRobbins',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='', max_length=20)),
                ('serving_size', models.IntegerField(default='115')),
                ('calory', models.IntegerField(default=0)),
                ('allergy', models.CharField(default='-', max_length=200)),
            ],
        ),
        migrations.DeleteModel(
            name='Fruit',
        ),
    ]
