# Generated by Django 3.2.3 on 2021-05-17 13:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('homepage', '0002_burger'),
    ]

    operations = [
        migrations.AlterField(
            model_name='burger',
            name='price',
            field=models.IntegerField(default=1000),
        ),
    ]
