# Generated by Django 3.2.3 on 2021-05-19 07:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('introduce', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='coffee',
            name='amount',
            field=models.IntegerField(default=0),
        ),
    ]
