# Generated by Django 3.1.4 on 2020-12-27 00:07

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Macaron',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='', max_length=50)),
                ('price', models.IntegerField(default=0)),
                ('is_ice_packaged', models.BooleanField(default=False)),
                ('ordered_time', models.DateTimeField(auto_now_add=True)),
                ('updated_time', models.DateTimeField(auto_now=True)),
                ('is_complete', models.BooleanField(default=False)),
            ],
        ),
    ]
