# Generated by Django 3.1.4 on 2020-12-27 01:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('macaronpage', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='macaron',
            name='is_complete',
        ),
        migrations.RemoveField(
            model_name='macaron',
            name='is_ice_packaged',
        ),
        migrations.RemoveField(
            model_name='macaron',
            name='ordered_time',
        ),
        migrations.RemoveField(
            model_name='macaron',
            name='updated_time',
        ),
    ]
