# Generated by Django 3.1.4 on 2020-12-27 05:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('macaronpage', '0002_auto_20201227_0147'),
    ]

    operations = [
        migrations.CreateModel(
            name='Stock',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.IntegerField(default=1)),
                ('warehouse_time', models.DateField(auto_now_add=True)),
                ('macaron_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='macaronpage.macaron')),
            ],
        ),
    ]
