# Generated by Django 3.1.4 on 2020-12-27 05:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('macaronpage', '0003_stock'),
    ]

    operations = [
        migrations.RenameField(
            model_name='stock',
            old_name='macaron_id',
            new_name='macaron',
        ),
    ]
