# Generated by Django 3.1.4 on 2020-12-27 06:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('macaronpage', '0004_auto_20201227_0526'),
    ]

    operations = [
        migrations.AddField(
            model_name='macaron',
            name='amount',
            field=models.IntegerField(default=0),
        ),
    ]
