# Generated by Django 3.2.2 on 2021-05-13 02:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('homepage', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='coffee',
            name='id',
            field=models.IntegerField(primary_key=True, serialize=False),
        ),
    ]
