# Generated by Django 3.1.4 on 2020-12-24 07:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('homepage', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Coffees',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='none', max_length=30)),
                ('is_ice', models.BooleanField(default=False)),
                ('price', models.IntegerField(default=0)),
                ('count', models.IntegerField(default=1)),
            ],
        ),
        migrations.DeleteModel(
            name='Coffee',
        ),
    ]
