# Generated by Django 3.2.3 on 2021-05-19 07:07

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Game',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(default='', max_length=75)),
                ('platform', models.CharField(default='', max_length=15)),
                ('genre', models.CharField(default='', max_length=15)),
                ('price', models.IntegerField(default=0)),
                ('stock', models.IntegerField(default=0)),
                ('reserved', models.IntegerField(default=0)),
                ('extinct', models.BooleanField(default=False)),
            ],
        ),
    ]
