# Generated by Django 3.2.3 on 2021-05-18 13:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('homepage', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='coffee',
            old_name='price',
            new_name='stock',
        ),
        migrations.RemoveField(
            model_name='coffee',
            name='is_ice',
        ),
    ]
