# Generated by Django 3.2.3 on 2021-05-19 07:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('homepage', '0002_icecream'),
    ]

    operations = [
        migrations.AddField(
            model_name='icecream',
            name='stock',
            field=models.IntegerField(default=0),
        ),
    ]
