# Generated by Django 3.2.3 on 2021-05-19 07:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('homepage', '0003_icecream_stock'),
    ]

    operations = [
        migrations.AddField(
            model_name='icecream',
            name='icecream_id',
            field=models.IntegerField(default=0),
        ),
    ]
