# Generated by Django 3.2.3 on 2021-05-19 08:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('homepage', '0004_icecream_icecream_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='icecream',
            name='icecream_id',
        ),
    ]
