# Generated by Django 3.2.3 on 2021-05-30 11:49

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('coffee', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='coffee',
            name='expiry_date',
        ),
        migrations.AddField(
            model_name='coffee',
            name='order_date',
            field=models.DateField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='coffee',
            name='cup_select',
            field=models.CharField(choices=[('IC', 'In Store Cup'), ('PC', 'Personal Cup'), ('DC', 'Disposable Cup')], default='IC', max_length=30),
        ),
    ]
