# Generated by Django 3.1.4 on 2020-12-28 07:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('homepage', '0002_phone_phonecompany'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='phone',
            name='company',
        ),
        migrations.AddField(
            model_name='phone',
            name='company',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.PROTECT, to='homepage.phonecompany'),
        ),
        migrations.AlterField(
            model_name='phone',
            name='price',
            field=models.IntegerField(),
        ),
    ]
