# Generated by Django 3.1.4 on 2020-12-28 07:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('homepage', '0003_auto_20201228_1636'),
    ]

    operations = [
        migrations.AlterField(
            model_name='phone',
            name='company',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='homepage.phonecompany'),
        ),
    ]
