# Generated by Django 3.2.3 on 2021-05-14 15:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('coffee', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='coffee',
            name='is_ice',
        ),
    ]
