{
 "cells": [
  {
   "cell_type": "markdown",
   "id": "0f1e1156",
   "metadata": {},
   "source": [
    "### GET\n",
    "\n",
    "- `GET/whoami`\n",
    "\n",
    "    - github id를 반환합니다.\n",
    "    - example:   \n",
    "    \n",
    "      {  \n",
    "          \"name\": \"github id\"  \n",
    "      }\n",
    "    \n",
    "    \n",
    "    \n",
    "- `GET/echo?string=\"string\"`\n",
    "\n",
    "    - Query String : `string`\n",
    "    - `string`을 반환합니다.   \n",
    "    \n",
    "      {\n",
    "           \"value\": \"corini\"\n",
    "      }\n",
    "    \n",
    "    \n",
    "    \n",
    "- `GET/weapon`\n",
    "\n",
    "    - 저장된 weapon의 정보를 가져옵니다.\n",
    "    - `Json` 타입의 weapon을 반환합니다. \n",
    "    \n",
    "      {\n",
    "          \"weapon\": [\n",
    "            {\n",
    "                \"name\": \"Shotgun\",\n",
    "                \"stock\": 1\n",
    "            }\n",
    "          ]\n",
    "      }"
   ]
  },
  {
   "cell_type": "markdown",
   "id": "4887b793",
   "metadata": {},
   "source": [
    "### POST\n",
    "\n",
    "- `POST/weapon`\n",
    "\n",
    "    - 새로운 `weapon`을 추가\n",
    "    - 성공시 새로운 `weapon`정보를 반환\n",
    "    - Body example:   \n",
    "    \n",
    "       { \n",
    "          \"name\": \"Shotgun\",  \n",
    "          \"stock\": 1\n",
    "       }\n",
    "        "
   ]
  },
  {
   "cell_type": "markdown",
   "id": "d824521c",
   "metadata": {},
   "source": [
    "### PUT\n",
    "\n",
    "- `PUT /weapon/<string:name>`\n",
    "\n",
    "    - 현재 존재하는 weapon에서 특정 속성(이름, 수량)을 변경\n",
    "    - `<string:name>`을 인자로 값 변경\n",
    "    - `weapons`의 값 JSON형식으로 반환\n",
    "    - Body example: \n",
    "    \n",
    "    \n",
    "       {\n",
    "          \"name\": \"Muchinegun\",  \n",
    "          \"stock\": 10\n",
    "       }\n",
    "    \n",
    "    \n",
    "    * 반환 성공시\n",
    "    \n",
    "    \n",
    "       {\n",
    "          \"weapons\": [\n",
    "            {\n",
    "                \"name\": \"Muchinegun\" \n",
    "                \"stock\": 10. \n",
    "            }\n",
    "          ]\n",
    "       } \n",
    "      \n",
    "      \n",
    "    * 반환 실패시\n",
    "     \n",
    "        - `<string:name>` 값이 존재하지 않는 경우\n",
    "          \n",
    "     Not Found weapon"
   ]
  },
  {
   "cell_type": "markdown",
   "id": "d0e35f9f",
   "metadata": {},
   "source": [
    "### DELETE\n",
    "\n",
    "- DELETE/weapon/<string:name>\n",
    "    - 현재 존재하는 특정 `weapon`을 삭제\n",
    "    - `<string:name>`을 인자로 값 삭제\n",
    "    - `weapons`의 값 JSON 형식으로 반환\n",
    "    - 삭제 성공시\n",
    "    \n",
    "      {  \n",
    "          \"weapons\": [  \n",
    "            {  \n",
    "              \"name\": \"Muchinegun\",  \n",
    "              \"stock\":10\n",
    "            }   \n",
    "           ]   \n",
    "      }  \n",
    "    \n",
    "    - 반환 실패시\n",
    "        - `<string:name>`값이 존재하지 않는 경우\n",
    "        \n",
    "    Not Found weapon"
   ]
  }
 ],
 "metadata": {
  "kernelspec": {
   "display_name": "Python 3",
   "language": "python",
   "name": "python3"
  },
  "language_info": {
   "codemirror_mode": {
    "name": "ipython",
    "version": 3
   },
   "file_extension": ".py",
   "mimetype": "text/x-python",
   "name": "python",
   "nbconvert_exporter": "python",
   "pygments_lexer": "ipython3",
   "version": "3.9.5"
  }
 },
 "nbformat": 4,
 "nbformat_minor": 5
}
